spring.jpa.hibernate.ddl-auto=update
cors.allowed-origin=http://localhost:3000
spring.datasource.url = jdbc:mysql://${MYSQL_HOST:localhost}:3306/ma_db?createDatabaseIfNotExist=true
#jdbc:mysql://database-2.ctninc04pir1.us-east-1.rds.amazonaws.com:3306/ma_db?createDatabaseIfNotExist=true
#jdbc:mysql://localhost:3306/data
spring.datasource.username=root
spring.datasource.password=no
spring.jpa.database-platform= org.hibernate.dialect.MariaDB102Dialect
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB